BEGIN;

CREATE TABLE IF NOT EXISTS public.cashfree_payment_intents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cashfree_order_id text NOT NULL UNIQUE,
  user_id uuid,
  customer_name text NOT NULL,
  customer_email text,
  phone text NOT NULL,
  address text NOT NULL,
  pincode text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  items jsonb NOT NULL,
  mrp_total numeric NOT NULL,
  product_total numeric NOT NULL,
  taxable_value numeric NOT NULL,
  gst_total numeric NOT NULL,
  cgst numeric NOT NULL DEFAULT 0,
  sgst numeric NOT NULL DEFAULT 0,
  igst numeric NOT NULL DEFAULT 0,
  delivery_charge numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','failed')),
  cashfree_payment_id text,
  cashfree_payment_status text,
  order_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS cashfree_payment_intents_status_idx
  ON public.cashfree_payment_intents (status, created_at);

ALTER TABLE public.cashfree_payment_intents ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.cashfree_payment_intents FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.cashfree_payment_intents TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.cashfree_payment_intents_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.create_paid_order_with_stock(p_payment_intent_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $function$
DECLARE
  intent record;
  item jsonb;
  slug text;
  qty integer;
  stock integer;
  current_status text;
  created_id bigint;
BEGIN
  SELECT * INTO intent FROM public.cashfree_payment_intents
  WHERE id = p_payment_intent_id FOR UPDATE;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('success',false,'message','Payment intent not found.');
  END IF;
  IF intent.order_id IS NOT NULL THEN
    RETURN pg_catalog.jsonb_build_object('success',true,'order_id',intent.order_id);
  END IF;
  IF intent.status <> 'pending' THEN
    RETURN pg_catalog.jsonb_build_object('success',false,'message','Payment intent is not pending.');
  END IF;

  FOR item IN SELECT element FROM pg_catalog.jsonb_array_elements(intent.items) AS items(element)
    ORDER BY element ->> 'product_slug'
  LOOP
    slug := item ->> 'product_slug';
    qty := NULLIF(item ->> 'quantity','')::integer;
    SELECT p.stock_quantity,p.status INTO stock,current_status
      FROM public.product_status p WHERE p.product_slug=slug FOR UPDATE;

    IF FOUND AND current_status IN ('hidden','coming-soon','out-of-stock') THEN
      RETURN pg_catalog.jsonb_build_object('success',false,'message','A product in this order is no longer available.');
    END IF;
    IF FOUND AND stock IS NOT NULL AND stock < qty THEN
      RETURN pg_catalog.jsonb_build_object('success',false,'message','There is not enough stock to fulfil this paid order.');
    END IF;
  END LOOP;

  FOR item IN SELECT element FROM pg_catalog.jsonb_array_elements(intent.items) AS items(element)
    ORDER BY element ->> 'product_slug'
  LOOP
    slug := item ->> 'product_slug';
    qty := (item ->> 'quantity')::integer;
    UPDATE public.product_status p
      SET stock_quantity=p.stock_quantity-qty,
          status=CASE WHEN p.stock_quantity-qty=0 THEN 'out-of-stock' ELSE p.status END
      WHERE p.product_slug=slug AND p.stock_quantity IS NOT NULL;
  END LOOP;

  INSERT INTO public.orders (
    user_id,customer_name,customer_email,phone,address,pincode,city,state,items,
    mrp_total,product_total,taxable_value,gst_total,cgst,sgst,igst,delivery_charge,total,
    payment_method,order_status,inventory_reserved,pending_expires_at
  ) VALUES (
    intent.user_id,intent.customer_name,intent.customer_email,intent.phone,intent.address,
    intent.pincode,intent.city,intent.state,intent.items,intent.mrp_total,intent.product_total,
    intent.taxable_value,intent.gst_total,intent.cgst,intent.sgst,intent.igst,intent.delivery_charge,
    intent.total,'Cashfree','confirmed',true,NULL
  ) RETURNING id INTO created_id;

  RETURN pg_catalog.jsonb_build_object('success',true,'order_id',created_id);
END;
$function$;

REVOKE ALL ON FUNCTION public.create_paid_order_with_stock(bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_paid_order_with_stock(bigint) TO service_role;

COMMIT;
