BEGIN;

CREATE TABLE IF NOT EXISTS public.retailer_order_status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  retailer_order_id bigint NOT NULL REFERENCES public.retailer_orders(id) ON DELETE CASCADE,
  old_status text,
  new_status text NOT NULL,
  note text,
  changed_by text,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS retailer_order_status_history_order_idx
  ON public.retailer_order_status_history(retailer_order_id, changed_at DESC);

ALTER TABLE public.retailer_order_status_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can manage retailer order status history"
  ON public.retailer_order_status_history;

CREATE POLICY "Admins can manage retailer order status history"
  ON public.retailer_order_status_history
  FOR ALL
  USING ((auth.jwt() ->> 'email') = 'info@tenoo.in')
  WITH CHECK ((auth.jwt() ->> 'email') = 'info@tenoo.in');

CREATE OR REPLACE FUNCTION public.log_retailer_order_status_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.retailer_order_status_history (
      retailer_order_id,
      old_status,
      new_status,
      note,
      changed_by
    )
    VALUES (
      NEW.id,
      NULL,
      NEW.order_status,
      NULL,
      auth.jwt() ->> 'email'
    );
    RETURN NEW;
  END IF;

  IF NEW.order_status IS DISTINCT FROM OLD.order_status
     OR NEW.notes IS DISTINCT FROM OLD.notes THEN
    INSERT INTO public.retailer_order_status_history (
      retailer_order_id,
      old_status,
      new_status,
      note,
      changed_by
    )
    VALUES (
      NEW.id,
      OLD.order_status,
      NEW.order_status,
      CASE
        WHEN NEW.order_status = 'cancelled'
             AND NEW.notes IS DISTINCT FROM OLD.notes
        THEN NEW.notes
        ELSE NULL
      END,
      auth.jwt() ->> 'email'
    );
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS retailer_order_status_history_trigger
  ON public.retailer_orders;

CREATE TRIGGER retailer_order_status_history_trigger
AFTER INSERT OR UPDATE OF order_status, notes
ON public.retailer_orders
FOR EACH ROW
EXECUTE FUNCTION public.log_retailer_order_status_change();

COMMIT;